# Some data handling with pandas
_Loto fácil is a Brazilian lottery where the winner hits 15 out of 25 possible numbers._

_1 in 3,268,760 Possibilities._

_These datasets will be used to:_
- _Read .xlsx file_
- _Files Consolidation_
- _Date Format Change_
- _Create DataFrame_
- _Rename Columns_
- _Multi-Index_
- _Sort Data_
- _Duplicated Values_
- _Count Values_
- _Filter Data_

In [1]:
# import library
import pandas as pd
import glob

In [2]:
# reading one of the files
pd.read_excel("files/loto_facil_2020_sorteio.xlsx").head(9)

,As Loterias - www.asloterias.com.br - Todos Resultados da Loto Fácil,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,Este arquivo foi baixado no site www.asloteria...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Visite o site para baixar a versão mais atuali...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,TODOS RESULTADOS DA LOTO FÁCIL DO ANO DE 2020 ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Concurso,Data,bola 1,bola 2,bola 3,bola 4,bola 5,bola 6,bola 7,bola 8,bola 9,bola 10,bola 11,bola 12,bola 13,bola 14,bola 15
6,1920,24/01/2020,6,13,14,21,11,9,20,4,10,17,18,22,25,2,12
7,1919,22/01/2020,24,11,21,10,15,3,9,1,6,2,19,20,5,22,23
8,1918,20/01/2020,17,19,7,18,2,12,20,4,5,9,10,24,11,22,6

In [3]:
# Files consolidation
all_files = glob.glob("files/loto_facil_*.xlsx")

li = []

for filename in all_files:
    df = pd.read_excel(filename, index_col=None, header=0)
    header = df.iloc[5] # get names to columns
    df = df[6:] # get data of 6th index to down
    df = df.rename(columns = header) # Rename columns
    df = df.sort_index(ascending=False) # Set index to descending
    df["Data"] = pd.to_datetime(df["Data"], format="%d/%m/%Y") # Date format change
    li.append(df)
    
drawn_df = pd.concat(li, axis=0, ignore_index=True)

In [4]:
# read columns
drawn_df.columns

Index(['Concurso', 'Data', 'bola 1', 'bola 2', 'bola 3', 'bola 4', 'bola 5',
       'bola 6', 'bola 7', 'bola 8', 'bola 9', 'bola 10', 'bola 11', 'bola 12',
       'bola 13', 'bola 14', 'bola 15'],
      dtype='object')

In [5]:
# Rename columns
drawn_df.columns = ['loto_facil', 'date', 'ball_1', 'ball_2', 'ball_3', 'ball_4', 'ball_5',
                    'ball_6', 'ball_7', 'ball_8', 'ball_9', 'ball_10', 'ball_11', 'ball_12', 
                    'ball_13', 'ball_14', 'ball_15']
#Set multi index
drawn_df.set_index(['loto_facil', 'date'], inplace = True)

In [6]:
drawn_df = drawn_df.sort_index(ascending=True)

In [7]:
# read first and last line
drawn_df.loc[[1, len(drawn_df)]]

,,ball_1,ball_2,ball_3,ball_4,ball_5,ball_6,ball_7,ball_8,ball_9,ball_10,ball_11,ball_12,ball_13,ball_14,ball_15
loto_facil,date,,,,,,,,,,,,,,,
1,2003-09-29,18,20,25,23,10,11,24,14,6,2,13,9,5,16,3
1920,2020-01-24,6,13,14,21,11,9,20,4,10,17,18,22,25,2,12

In [8]:
# read the last five line
drawn_df.tail()

,,ball_1,ball_2,ball_3,ball_4,ball_5,ball_6,ball_7,ball_8,ball_9,ball_10,ball_11,ball_12,ball_13,ball_14,ball_15
loto_facil,date,,,,,,,,,,,,,,,
1916,2020-01-15,20,11,4,7,24,15,6,25,10,13,18,23,19,5,8
1917,2020-01-17,2,24,23,3,20,14,19,4,1,25,10,15,21,13,17
1918,2020-01-20,17,19,7,18,2,12,20,4,5,9,10,24,11,22,6
1919,2020-01-22,24,11,21,10,15,3,9,1,6,2,19,20,5,22,23
1920,2020-01-24,6,13,14,21,11,9,20,4,10,17,18,22,25,2,12

_**Note:** Describing the data frame, we can see the most drawn number in each position._

In [9]:
# Describe dataframe
drawn_df.describe()

,ball_1,ball_2,ball_3,ball_4,ball_5,ball_6,ball_7,ball_8,ball_9,ball_10,ball_11,ball_12,ball_13,ball_14,ball_15
count,1920,1920,1920,1920,1920,1920,1920,1920,1920,1920,1920,1920,1920,1920,1920
unique,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25
top,1,7,12,5,8,11,3,9,20,2,6,4,14,2,23
freq,96,94,92,91,97,95,88,98,104,98,91,92,94,96,93

_Transforming the data frame to array._

In [10]:
matrix = drawn_df.values
matrix

array([[18, 20, 25, ..., 5, 16, 3],
       [23, 15, 5, ..., 9, 13, 7],
       [20, 23, 12, ..., 9, 17, 24],
       ...,
       [17, 19, 7, ..., 11, 22, 6],
       [24, 11, 21, ..., 5, 22, 23],
       [6, 13, 14, ..., 25, 2, 12]], dtype=object)

_bubble_sort function to array sorting_

In [11]:
def bubble_sort(alist):
    for passnum in range(len(alist)-1, 0, -1):
        for i in range(passnum):
            if alist[i] > alist[i+1]:
                temp = alist[i]
                alist[i] = alist[i+1]
                alist[i+1] = temp


i = 0
while i < len(matrix):
    bubble_sort(matrix[i])
    i = i + 1

_Ordered array._

In [12]:
matrix

array([[2, 3, 5, ..., 23, 24, 25],
       [1, 4, 5, ..., 20, 23, 24],
       [1, 4, 6, ..., 20, 23, 24],
       ...,
       [2, 4, 5, ..., 20, 22, 24],
       [1, 2, 3, ..., 22, 23, 24],
       [2, 4, 6, ..., 21, 22, 25]], dtype=object)

_**Note:** Creating the `lottery_df` using `matrix` and `drawn_df`'s index._

In [13]:
# Create dataframe
lottery_df = pd.DataFrame(matrix, index=drawn_df.index, 
                           columns=list(['num_1', 'num_2', 'num_3', 'num_4','num_5',
                                         'num_6', 'num_7','num_8', 'num_9', 'num_10',
                                         'num_11', 'num_12', 'num_13','num_14', 'num_15']))

_In the `lottery_df`, the numbers are ascending._

In [14]:
# Read the last five line
lottery_df.tail()

,,num_1,num_2,num_3,num_4,num_5,num_6,num_7,num_8,num_9,num_10,num_11,num_12,num_13,num_14,num_15
loto_facil,date,,,,,,,,,,,,,,,
1916,2020-01-15,4,5,6,7,8,10,11,13,15,18,19,20,23,24,25
1917,2020-01-17,1,2,3,4,10,13,14,15,17,19,20,21,23,24,25
1918,2020-01-20,2,4,5,6,7,9,10,11,12,17,18,19,20,22,24
1919,2020-01-22,1,2,3,5,6,9,10,11,15,19,20,21,22,23,24
1920,2020-01-24,2,4,6,9,10,11,12,13,14,17,18,20,21,22,25

_Making sure there are no similar games._

In [15]:
lottery_df[lottery_df.duplicated()]

Empty DataFrame
Columns: [num_1, num_2, num_3, num_4, num_5, num_6, num_7, num_8, num_9, num_10, num_11, num_12, num_13, num_14, num_15]
Index: []

_**Note:** Now describing the data frame, we can see the variation of each position and number that appeared the most._

In [16]:
# Describe dataframe
lottery_df.describe()

,num_1,num_2,num_3,num_4,num_5,num_6,num_7,num_8,num_9,num_10,num_11,num_12,num_13,num_14,num_15
count,1920,1920,1920,1920,1920,1920,1920,1920,1920,1920,1920,1920,1920,1920,1920
unique,6,8,9,9,10,10,11,11,11,11,10,10,9,8,8
top,1,2,4,6,8,10,11,14,15,16,19,20,22,24,25
freq,1168,686,527,417,375,369,374,377,401,386,416,471,506,715,1164

_**Note:** In the column `'num_1'`, we can see the amount of the smallest numbers drawn._

In [17]:
# value_counts()
lottery_df['num_1'].value_counts().to_frame()

   num_1
1   1168
2    478
3    188
4     50
5     32
6      4

_Let’s  see when number six was the smallest number drawn._

In [18]:
# Filter data
lottery_df[lottery_df.num_1 == 6] # or => lottery_df[lottery_df['num_1'] == 6]

,,num_1,num_2,num_3,num_4,num_5,num_6,num_7,num_8,num_9,num_10,num_11,num_12,num_13,num_14,num_15
loto_facil,date,,,,,,,,,,,,,,,
576,2010-10-21,6,8,9,10,11,12,13,15,16,17,18,19,21,23,25
815,2012-10-13,6,7,8,10,11,14,15,17,18,20,21,22,23,24,25
1336,2016-03-16,6,8,9,10,11,12,13,14,15,17,18,19,20,22,24
1352,2016-04-22,6,8,10,11,12,13,14,15,16,19,20,21,23,24,25

_Transforming array into two columns_

In [19]:
def array_into_2columns(alist):
    li = []
    for ind in range(len(alist)):
        for col in range(len(alist[0])):
            li.append([ind+1,alist[ind][col]])
            
    return li

two_columns = array_into_2columns(matrix)

In [20]:
two_columns_df = pd.DataFrame(two_columns, columns=['loto_facil','number'])
two_columns_df.set_index('loto_facil', inplace=True)
two_columns_df.tail()

            number
loto_facil
1920            18
1920            20
1920            21
1920            22
1920            25

_Count numbers._

In [21]:
most_drawn = two_columns_df['number'].value_counts().to_frame(name="Count numbers")
most_drawn

    Count numbers
13           1188
24           1184
11           1180
10           1175
20           1171
14           1169
1            1168
25           1164
4            1164
2            1164
3            1158
5            1154
18           1153
19           1153
23           1151
17           1148
15           1148
22           1148
21           1147
12           1138
9            1132
7            1126
6            1121
16           1100
8            1096